### ISSUE TITLE
Better debug support when running benchmark from the image

### ISSUE THREAD

**Issue by htejun** [iocost-benchmark/resctl-demo-image-recipe#10]
The usb installation image for resctl-bench is generated from the following git repo using its CI pipeline:
https://github.com/iocost-benchmark/resctl-demo-image-recipe

While the image works more or less, it can be difficult to debug what happened after a benchmark failure. Here's a list of possible improvements:

1. Unfortunately, resctl-bench sometimes crashes (e.g. there's a latent rd-hashd bug which sometimes causes segfault). Because the results are accumulated over time into the result file, just re-running the same command usually solves the issue by continuing from the last failure point. Unfortunately, the benchmark script in the image doesn't do that currently. It'd be useful to add a limited number of retries on resctl-bench failures. See https://github.com/iocost-benchmark/resctl-demo-image-recipe/blob/main/overlays/resctl-demo/home/demo/start-resctl-bench 

2. resctl-bench's output on the console can be useful in understanding what happened; however, the only way to capture them now is taking a photo or capturing from an external terminal. It'd be useful to record the outputs a log file. This might require resctl-bench code changes.

3. Sometimes SSDs fail (e.g. drops off of the bus and stops responding) while benchmark is running. This is an important clue indicating a possible reliability problem for the SSD model if observed across multiple devices. However, because the whole system is hosted on the SSD, the ultimate failure mode is unpredictable and can often lead to non-functioning system by which point it can be difficult to gather enough data to understand what happened. It'd be useful to capture the kernel messages and store them on the usb stick. Note that this would have to be continuous as the system might not be functional enough after such failures.
4. The benchmarks run for hours and we already require a pretty big USB stick. It'd be nice if we can store resctl-bench pack result into the usb stick. This would help debugging resctl-bench crashes quite a bit.

**Comment by saravan2** [comment]
Update [6/28/23] to existing issue :
@santoshmahto7, @htejun, @saravan2 

Add [rust] backtrace support when test fails, preserve all logging. 
We dropped the idea of coredump as we wont have storage space in the USB to store.

**Comment by santoshmahto7** [comment]
Two PR in different repo has been added for this. review will be welcomed
resctl-demo-image-recipe: https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/19
resctl-demo:  https://github.com/facebookexperimental/resctl-demo/pull/293
