### ISSUE TITLE
Develop test script to use nmtui utility

### ISSUE THREAD

**Issue by saravan2** [iocost-benchmark/resctl-demo-image-recipe#11]
When nmtui is added to the image as part of : https://github.com/iocost-benchmark/resctl-demo-image-recipe/issues/9 
We should modify the test script to allow the user to configure network and upload the test results.

**Comment by santoshmahto7** [comment]
WIP PR: https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/15

**Comment by saravan2** [comment]
@davide125 Do we have a public AWS S3 Bucket endpoint where volunteers can submit the resctl-bench solutions ?

@santoshmahto7 Would redesign the script to upload the solution to that endpoint.

**Comment by santoshmahto7** [comment]
There is already an upload mechanism available in resctl-bench which uploads result to S3 bukcet with the help of lambda.
e.g
```
resctl-bench --resullt xxx-xxxx.json.gz  upload --upload-url <LAMBDA FUNCTION URL> 
resctl-bench --result resctl-bench-result_2023_05_01-19_18_49_1.json.gz upload --upload-url https://ygvr6jnjckwamfao5xztg6idiu0ukjeb.lambda-url.eu-north-1.on.aws/
```
Thus once lambda is operational, upload will automatically work together with issue update in iocost-benchmarks.
This task will only be required in case user want standalone upload without triggering lambda just to store his benchmarks.

**Comment by ewyler** [comment]
Sounds like this task is done if uploading to the API works. We wouldn't' want someone to be able to upload directly to the bucket - that's what the API is for, to control access. If someone wants to store benchmarks somewhere special for some reason, they can do that locally

**Comment by ewyler** [comment]
Though:

> Thus once lambda is operational, upload will automatically work together with issue update in iocost-benchmarks.

Is the lambda operational now or is there more work to do?

**Comment by santoshmahto7** [comment]
> Though:
> 
> > Thus once lambda is operational, upload will automatically work together with issue update in iocost-benchmarks.
> 
> Is the lambda operational now or is there more work to do?

All the code is merged, Last remaining  thing is verifying/testing the deployment with internal  AWS setup as tracked by task https://github.com/iocost-benchmark/iocost-benchmarks-ci/issues/16. Someone from facebook team need to do that since I don't have internal aws access (Although I have tested in my aws local setup)

**Comment by ewyler** [comment]
I've pinged Davide to ask him to test this to verify it for you

**Comment by ewyler** [comment]
He'll test it next week

**Comment by ewyler** [comment]
This upload capability is already in the benchmark, so this isn't needed anymore
