### ISSUE TITLE
Upload built image to AWS EC2 repo fails due to invalid credentials

### ISSUE THREAD

**Issue by saravan2** [iocost-benchmark/resctl-demo-image-recipe#16]
Upload Legacy boot image to AWS EC2 step

https://github.com/iocost-benchmark/resctl-demo-image-recipe/actions/runs/5373738169/workflow#L119

```
        env:
          EC2_ACCESS_ID: ${{ secrets.EC2_ACCESS_ID }}
          EC2_SECRET_KEY: ${{ secrets.EC2_SECRET_KEY }}
          EC2_REGION: ${{ secrets.EC2_REGION }}
          EC2_BUCKET: ${{ secrets.EC2_BUCKET }}
```

Error 

```
Traceback (most recent call last):
  File "/home/runner/work/resctl-demo-image-recipe/resctl-demo-image-recipe/aws-ec2/cleanup-aws-ec2.py", line 36, in <module>
    images = ec2_client.describe_images(Owners=['self'])
  File "/home/runner/.local/lib/python3.10/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/botocore/client.py", line 911, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeImages operation: AWS was not able to validate the provided access credentials
Error: Process completed with exit code 1.
````

**Comment by saravan2** [comment]
@davide125  Do have to update the secrets for this Build Action to succeed ?

**Comment by davide125** [comment]
I think we'd concluded that this wasn't actually needed? At least that's what I remembered from our last conversation with @htejun and that's why you're getting that error, as the existing account was decommissioned. If it turns out we do still need this we'll need to spin up another bucket for it on our end.

**Comment by obbardc** [comment]
If we don't upload the system images to EC2, people can still download the artifacts and run the images locally or upload to a cloud service themselves.

@santoshmahto7 can we just remove the upload step from the CI?

**Comment by saravan2** [comment]
Closing this issue.

**Comment by santoshmahto7** [comment]
PR: https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/17

**Comment by ewyler** [comment]
Closing per above comments, this task isn't needed
