### ISSUE TITLE
CI build failing

### ISSUE THREAD

**Issue by santoshmahto7** [iocost-benchmark/resctl-demo-image-recipe#20]
The current build is failing:
```
023/08/24 12:26:02 ==== Compress resctl-demo-image-efiboot.img ====
2023/08/24 12:26:02 pigz -f -k "$ARTIFACTDIR/resctl-demo-ima... | sh: 1: pigz: not found
2023/08/24 12:26:02 Action `Compress resctl-demo-image-efiboot.img` failed at stage PostMachine, error: exit status 127
```
More details: https://github.com/iocost-benchmark/resctl-demo-image-recipe/actions/runs/5963419182/job/16176582440

**Comment by obbardc** [comment]
Need to install pigz in the docker container :-).

**Comment by santoshmahto7** [comment]
Right,  It was working before so it seems now it doesn't exist anymore in ubuntu:latest  by default and need install manually

**Comment by obbardc** [comment]
Need to install it under https://github.com/iocost-benchmark/resctl-demo-image-recipe/blob/main/ci-image-builder/Dockerfile

**Comment by santoshmahto7** [comment]
Another PR created to fix another disk space issue in CI: https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/22

```
2023/08/24 23:48:38 ==== Compress resctl-demo-image-legacyboot.img ====
2023/08/24 23:50:17 pigz -f -k "$ARTIFACTDIR/resctl-demo-ima... | pigz: abort: write error on /home/runner/work/resctl-demo-image-recipe/resctl-demo-image-recipe/out/resctl-demo-image-legacyboot.img.gz (No space left on device)
2023/08/24 23:50:17 Action `Compress resctl-demo-image-legacyboot.img` failed at stage PostMachine, error: exit status 28
Error: Process completed with exit code 1.
```

**Comment by santoshmahto7** [comment]
CI is fixed so closing this issue.
