### ISSUE TITLE
Latest flasher image failing to boot properly

### ISSUE THREAD

**Issue by santoshmahto7** [iocost-benchmark/resctl-demo-image-recipe#27]
Latest flasher image fails to boot while mounting ext4 filesystem

Reason : We have started using resctl-demo kernel instead of debian default. It seems resctl-demo kernel only support btrfs filesystem and ext4 support is disabled.  But flasher image has to mount partition as ext4 where it stores installation image.

There are two solution other than revert to Debian default for kernel.
1. Enable support of ext4 filesystem in resctl-demo // better solution
2. Use btfs also for installation image storage  // won't suite btrfs unsupported system

@obbardc @htejun

**Comment by htejun** [comment]
Let's enable ext4 in the resctl-demo kernel config. I can't think of a downside for that.

**Comment by santoshmahto7** [comment]
This original issue is fixed with the mentioned PR, i.e flasher image boot properly now. 

But it seems, image installation on target device still have some issue and also kexec fails. The reason is that it fails to load some other required module specifically btrfs, vfat, nls_cp437 and thus fails to mount the target device when required to set some settings.

I have created another pull request to address this issue.
https://github.com/iocost-benchmark/resctl-demo-linux/pull/5
@htejun @obbardc

**Comment by santoshmahto7** [comment]
This issue is fixed with resctl-demo-linux patch
