### ISSUE TITLE
Develop dependabot to maintain, update Github actions

### ISSUE THREAD

**Issue by saravan2** [iocost-benchmark/resctl-demo-image-recipe#8]
All existing github action regressions have been fixed. We could start developing dependabot to maintain the github actions

**Comment by santoshmahto7** [comment]
PR created : https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/12

**Comment by saravan2** [comment]
Merged https://github.com/iocost-benchmark/resctl-demo-image-recipe/pull/12
